#!/bin/sh
### BEGIN INIT INFO
# Provides:          svn_serve
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the HTTP Proxy.
### END INIT INFO
case $1 in
    start)
        sudo sh /home/pi/crysadm/run.sh
        ;;
    stop)
        sudo sh /home/pi/crysadm/down.sh
        ;;
*)
echo "Usage: $0 (start|stop)"
;;
esac
